credentials:
  usernames:
    emmanuel:
      email: tettehosabutey49@gmail.com
      #failed_login_attempts: 0 # Will be managed automatically
      logged_in: False # Will be managed automatically
      name: Emmanuel Osabutey
      password: "00000" # Will be hashed automatically
    
cookie:
  expiry_days: 0
  key: some_signature_key # Must be string
  name: some_cookie_name
pre-authorized:
  emails:
  - emmanuel.osabutey@azubiafrica.org